version: '3.5'
name: 'rinha-backend'

services:
  api1: # API - Instância 01
    build: .
    container_name: cadpessoa
    hostname: api1
    environment:
      DATASOURCE_HOST: db
#      DATASOURCE_SCHEMA: cadastro
#      DATASOURCE_USERNAME: root
#      DATASOURCE_PASSWORD: root
#      SERVER_MAX_POOL: 30
#      DATABASE_MAX_POOL: 30
#      JAVA_TOOL_OPTIONS: "-verbose:gc"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9999:9999
      - 9010:9010
    deploy:
      resources:
        limits:
          cpus: '1.2'
          memory: '1.5GB'
    networks:
      - networker

  db: # Banco de dados
    image: mysql:8.4.0
    container_name: mysqlcomp
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
      test: "mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\" || exit 1"
      start_period: 4s
      interval: 4s
      timeout: 6s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '1.5GB'
    networks:
      - networker

networks:
  networker: {}