server:
  port: 9999
#  tomcat:
#    threads:
#      max: 1
#      min-spare: 1
#    max-connections: 1000
#    accept-count:  10


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cadastro?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog-master.xml
  cache:
    type: Caffeine #Não precisa. Apenas para facilitar na visualização
  jpa:
    hibernate:
      #Valida na inicialização do sistema, se o JPA conseguirá se comunicar com as entidades definidas
      ddl-auto: validate
      naming:
        #Para encontrar tabelas uppercase no banco de dados, por padrão o hibernate busca tudo com lowercase
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        orm:
#          jdbc:
#            bind: TRACE
